version: '3.8'
services:
  app:
    image: ghcr.io/pingfu/cgmsharp/cgmsharp:latest
    container_name: cgmsharp
    environment:
      - LIBRE_USERNAME=your_libre_username
      - LIBRE_PASSWORD=your_libre_password
      - LIBRE_AGENT_VERSION=4.12.0
      - NTFY_TOPIC_ALERT=your_ntfy_alert_topic
      - NTFY_TOPIC_CANARY=your_ntfy_canary_topic
      - NTFY_TOPIC_NUDGE=your_ntfy_nudge_topic